module.exports = {
  PingReserveNow: require('./executions/PingReserveNow'),
  ChangeConnectorAvailability: require('./executions/ChangeConnectorAvailability'),
  ChangeStationConfiguration: require('./executions/ChangeStationConfiguration'),
  PingAndRemoteStartTransaction: require('./executions/PingAndRemoteStartTransaction'),
  PingAndRemoteStopTransaction: require('./executions/PingAndRemoteStopTransaction'),
  PingAndStartTransaction: require('./executions/PingAndStartTransaction'),
  PingAndReset: require('./executions/PingAndReset'),
  BootNotification: require('./executions/BootNotification'),
  Heartbeat: require('./executions/Heartbeat'),
  UpdateFlagAuthorize: require('./executions/UpdateFlagAuthorize'),
  UpdateFlagStartTransaction: require('./executions/UpdateFlagStartTransaction'),
  UpdateFlagStopTransaction: require('./executions/UpdateFlagStopTransaction'),
  NotifyMeterValues: require('./executions/NotifyMeretValues'),
  PingCarDetected: require('./executions/PingCarDetected'),
};
